---
- hosts: all
  tasks:
    - name: HTTP OS Package Installation
      package: name=httpd state=present
    - name: NTP File Configurations
      copy: source=./index.html destination=/var/www/html/index.html
    - name: To start HTTP services
      service: name=httpd state=started enabled=yes

